### PR TITLE
fix for "Klocwork plugin does not work in a master/slave configuration"

### PR DESCRIPTION
**Pull request by avri-schneider**
https://issues.jenkins-ci.org/browse/JENKINS-29673

### CODE REVIEW

**Comment by Aravindan** [comment]
I will do some tests this week and merge the pull request.

**Comment by avri-schneider** [comment]
Thanks, looking forward :+1:

**Comment by Aravindan** [comment]
Merge tested and done

**Comment by Aravindan** [comment]
A new version should be delivered soon

**Comment by avri-schneider** [comment]
Thanks! :)

**Pull request merged**
